name: simple_git
description: Simple git package inspired in nodejs simple-git. This package provide sync and async methods
version: 0.1.6
homepage: https://github.com/emanuel-braz/simple_git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  simple_process: ^0.1.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
